### ISSUE TITLE
where is ~/Dropbox/master.bib

### ISSUE THREAD

**Issue by joebling** [svmiller/svm-r-markdown-templates#1]
hi,
when i compile the svm-rmarkdown-syllabus-example.Rmd, I failed it because of the missing of  ~/Dropbox/master.bib in line 44? 

Can you upload all of the files in need, please?

**Comment by svmiller** [comment]
I don't think my master.bib is necessarily a file of need for the template. It's also an enormous .bib file that I've been making for the past seven years. You can just as well substitute your own .bib file for your own file.

Here would be an example entry for the `vasquez2009twp` citation.

@Book{vasquez2009twp,
  Title                    = {The War Puzzle Revisited},
  Author                   = {Vasquez, John A},
  Publisher                = {New York, NY: Cambridge University Press},
  Year                     = {2009}
}

**Comment by ThomasPepperz** [comment]
I think this issue can be closed. To reiterate the point of @svmiller you shouldn't need it but if you're having difficulty knitting the R Markdown template just copy and paste his bibliography example into a text editor and save it with the .bib extension.

After this, modify the ~/Dropbox/master.bib file path to match where you saved the newly-created master.bib file. 

Note "~" assumes you're on a Mac and represents your home directory.
