### ISSUE TITLE
adding twitter handle

### ISSUE THREAD

**Issue by GeoMicroSoares** [svmiller/svm-r-markdown-templates#12]
How would you go on about adding your twitter handle to the CV template?
Wanted to include their logo as well as you added i.e. the Github one.

Thanks for this - amazing resource!

**Comment by weiyangtham** [comment]
I just did this so here's my solution in case it's helpful. If @svmiller thinks it's right I'm happy to create a pull request for LinkedIn and Twitter icons.

Essentially you need to modify the `svm-latex-cv.tex` file. If you go to around line 240 of that file, you'll see a chunk of code enclosed in curly brackets that starts with `$if(email)$$if(fontawesome)$\faEnvelopeO \hspace{1 mm}$else$\emph{E-mail:}$endif$ \href{mailto:}{\tt $email$}`. You can add a similar line for Twitter: 

`$if(twitter)$$if(fontawesome)$\faTwitter \hspace{1 mm}$else$\emph{Twitter:}$endif$ \href{https:/twitter.com/$twitter$}{\tt $twitter$} \hspace{1 mm} $endif$`

I added this line between `$endif$` and `$if(updated)$`. 

From here, you can add the following to the YAML in your `.rmd` file 

`twitter: mytwitterhandle`

FYI, if you want to add your own icons, you can find the command for the icon you want [here](http://mirror.las.iastate.edu/tex-archive/fonts/fontawesome/doc/fontawesome.pdf). E.g. in this case `\faTwitter` is the Twitter icon.

**Comment by GeoMicroSoares** [comment]
Thanks so much @weiyangtham that worked perfectly.

**Comment by svmiller** [comment]
Thank you for doing that, and yeah, it's a simple fix (albeit with a lot of code). I added it to the template and pushed it to the directory.
