### ISSUE TITLE
I can't compile Rmd files due to lack of files

### ISSUE THREAD

**Issue by Frank-Sw** [svmiller/svm-r-markdown-templates#14]
I have tried, but after check the error, i realized the package has lack of complete files to run the code, like the logo as an instance.

**Comment by dalefrakes** [comment]
I have the same problem.  I think what's missing is the `master.bib` file and the `attendance-grades-relationship.csv file`.  I was only able to render a PDF after removing the entire attendance section and creating my own .bib file (however it did not correctly render the information from the file).

**Comment by svmiller** [comment]
Ohh, I didn’t even think that might be at the core of what’s happening here.

I’m currently between flights from Madrid and Seattle. In the next few days, I’ll upload (anonymizes!) attendance data from my actual classes and a sample bib file to this directory and adjust the template accordingly. Right now, you can just set `eval=F` in those relevant chunks and you should be fine.

**Comment by svmiller** [comment]
I uploaded some MWEs for the grade-relationships data and a simple .bib file that should get it to compile. I'll keep this open for a while but the hope is it should compile for you now without having to change anything else.
