### ISSUE TITLE
Add markdown-based unordered lists using the CV template

### ISSUE THREAD

**Issue by mattwarkentin** [svmiller/svm-r-markdown-templates#19]
Hi,

Thank you very much for providing all of these great templates. I am trying to convert my CV from a Word document to a Rmd document so I no longer have to deal with manual formatting pains and I can now git-track the Rmd for reproducibility.

I am interested in adding unordered lists and sub-items using Markdown, but it doesn't seem to be supported in the way I would expect. The list items are properly indented, but there are not "bullets" in front of the text.

I anticipated that using * and + for major and sub-items, respectively, they would look like this:

* Item
     + sub-item

Am I doing something wrong or does your template not support the bullet-points for lists?

**Comment by svmiller** [comment]
It's something I build into the template. You can customize it in the `svm-latex-cv.tex` file in the repo. Money passage would be here:

```
% Make lists without bullets
\renewenvironment{itemize}{
  \begin{list}{}{
    \setlength{\leftmargin}{1.5em}
  }
}{
  \end{list}
}


% Make parskips rather than indent with lists.
\usepackage{parskip}
\usepackage{titlesec}
\titlespacing\section{0pt}{12pt plus 4pt minus 2pt}{4pt plus 2pt minus 2pt}
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{4pt plus 2pt minus 2pt}
```

**Comment by warkentinmatt** [comment]
Thanks for the response. 

I am pretty novice with LaTeX outside of using it for writing some equations in Rmd documents. Any insight into how I can make the list have just the simple two-level cascading as shown in my original post (i.e. first bullet is filled circle, second-level is hollow circle)?
