### ISSUE TITLE
cslreferences missing in svm-latex-ms

### ISSUE THREAD

**Issue by ashenkin** [svmiller/svm-r-markdown-templates#30]
Hi there,
I use your svm-latex-ms (thank you!), but it seems to be crashing in recent Rstudio updates due to CSLReferences missing.  Wondering if you'd consider patching it for this?
Many thanks!

**Comment by svmiller** [comment]
I seem to vaguely recall this error working on something else. Basically, if you're using Pandoc/CSL (in lieu of natbib) for references, Rstudio's Pandoc will insert some kind of `CSLReferences` tag to wrap the references. If my template doesn't have it, LaTeX throws up an error that basically balks at the `CSLReferences` tag.

Could you do me a favor. First, can you see if this is still the case (probably is) in [my `{stevetemplates}` package](http://svmiller.com/stevetemplates/). You can download this package on CRAN. This particular Github repo is no longer actively maintained and I'm trying to direct users to the R package (which is actively maintained). The particular template there is `stevetemplates::article`. The usage should be fairly straightforward, especially if you're in Rstudio.

Second, if you're open to using one of my templates---any of them for this purpose---might I interest you in `stevetemplates::article2`? I [wrote this template last September](http://svmiller.com/blog/2020/09/another-rmarkdown-article-template/) and I *know* for a fact this issue won't arise with it.

**Comment by ashenkin** [comment]
Thanks for the reply!  Yep, seems fixed in your package, where you've included references to CSLReferences.  Many thanks!  I'll be using your nice package from now on.

**Comment by svmiller** [comment]
Perfect! I'm glad this has a happy resolution.
