### ISSUE TITLE
shenanigans with fonts

### ISSUE THREAD

**Issue by EgorZay** [svmiller/svm-r-markdown-templates#5]
hey man >

look, i am confused about `fontfamily:` using your template to create manuscripts.
how to change fonts using that? seems like i gotta tweak the .tex template file first, as this command:

`\newcommand*{\authorfont}{\fontfamily{phv}\selectfont}`

so the value `phv` is possible to change but i still i can't get anything to work.
i tried to use `ptm` and tweak `fontfamily:` to `Times` but it shouted that i didn't have Times.sty file.

could you thus provide me with little insight on that? i would solely appreciate that! >

offtopic: you rock
E.

**Comment by EgorZay** [comment]
also how to tweak `fontsize` of sections like 'Introduction' and 'Conclusion'?

**Comment by svmiller** [comment]
Curious, which template are you referencing? The manuscript one?

**Comment by svmiller** [comment]
Oh, and one point: pretty sure `fontfamily` is case-sensitive. You may not have a Times.sty file but you should have a times.sty file.

**Comment by EgorZay** [comment]
hm. okay, and yes -- the manuscript one

so i opened svm-latex-ms.tex

`\newcommand*{\authorfont}{\fontfamily{phv}\selectfont}`

changed to `ptm` instead of `phv`
then in `fontfamily:` i stated `times` in my .rmd file

and IT WORKED. nice

ps. so descriptive as anyone stumbles on it later.

thank you,
E.

**Comment by svmiller** [comment]
Also, if you want to tweak section fonts, call in the `secsty` package in LaTeX and start fudging it to get something you like. Here's a good primer on it: http://tex.stackexchange.com/questions/103286/how-to-change-section-subsection-font-size

**Comment by EgorZay** [comment]
thank you, sir
