### ISSUE TITLE
Suggestion/Bug fix: support \tightlist

### ISSUE THREAD

**Issue by briatte** [svmiller/svm-r-markdown-templates#7]
Pandoc (at least until version 1.17) treats

```md
- a
- b
- c
```

as a tightlist, using the `\tightlist` command when converting to TeX.

By default, the `latex-ms` template does not understand that command, and breaks if the document contains such a list.

The problem does not reproduce if `*` is used instead of `-` to build the list, which I find a bit puzzling to be honest.

Anyway, "tight lists" can easily be supported by copy-pasting [this bit of code](https://tex.stackexchange.com/a/258486/4191) in the preamble of the TeX template:

```tex
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```

**Comment by svmiller** [comment]
Easy enough addition. Pretty sure that came standard in the default pandoc template but my smashing of that template left a lot of things like that on the cutting floor.

Thanks for this and the other suggestion.
